security:
    encoders:
        App\Entity\Admin : 
            algorithm : auto
        App\Entity\Proprietaire : 
            algorithm : bcrypt
        App\Entity\Visiteur : 
            algorithm : bcrypt
        App\Entity\Locataire : 
            algorithm : bcrypt
            
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider :
            entity:
                class : App\Entity\Admin
                property : username 
        proprio : 
            entity :
                class : App\Entity\Proprietaire
                property : username
        visiteur : 
            entity :
                class : App\Entity\Visiteur
                property : username
        loc : 
            entity:
                class : App\Entity\Locataire
                property : username
        users : 
            chain:
                providers : [app_user_provider,  proprio, visiteur, loc]
         
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                provider : users
                authenticators:
                    - App\Security\AdminAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
        
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/visiteur, roles: ROLE_USER }
        - {path : ^/proprio, roles : ROLE_PROPRIO }
        - {path : ^/locataire, roles : ROLE_LOC }

    role_hierarchy : 
        ROLE_PROPRIO : ROLE_USER
        ROLE_ADMIN : ROLE_PROPRIO
        

