vich_uploader:
    db_driver: orm

    mappings:
        appart_image : 
            uri_prefix : images/appartements
            upload_destination : '%kernel.project_dir%/public/images/appartements'
            
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
